import createClient from "openapi-fetch";
import type { paths } from "./schema";

/**
 * HTTP client typed against the contract in openapi/openapi.yaml.
 *
 * The types come from schema.d.ts, generated by `npm run api:types`. That means
 * the path, method, query string, request body and response are all checked at
 * compile time: requesting a route that is not in the contract, or reading a
 * field the contract does not declare, does not compile.
 *
 * Usage:
 *
 *   import { apiClient } from "@/lib/api/client";
 *
 *   const { data, error } = await apiClient.GET("/health");
 *   if (error) return;          // here `error` is the Error schema
 *   console.log(data.status);   // here `data` is HealthStatus
 *
 * Note there is no `try/catch`: openapi-fetch returns `{ data, error }` and
 * TypeScript's narrowing does the rest.
 */
export const apiClient = createClient<paths>({
	baseUrl: process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000",
});
